### ISSUE TITLE
Losing pokemobs

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#116]
#### Issue Description:

when you throw the pokeball with your pokemon there is a chance that it won't appear and you will lose it
#### What happens:

i was leveling up my oshawott by fighting with zubats then i throwed it in to a zubat that was flying but i missed it and the pokeball with my oshawott dissapeared i think that it entered in a unloaded chunk
#### What you expected to happen:

it should not disappear
#### Steps to reproduce:

1.hold the right button too long and throw the pokeball with your pokemon
2.and maybe  the pokeball will get too far away in a unloaded chunk
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:3.6.2
- Pokecube Revival (if applicable):3.5.0
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
I haven't got this replicated yet, once I do, I will see about fixing it.

**Comment by jochuan** [comment]
Something strange happened, i won of a lass with my marshtomp and then i walked a little and then the message saying that the pokemon returned to my inventory appeared even without me pressing anything then i found one apple on the ground and one sapling and i picked it up but when i looked in the slot where the marshtomp was it were replaced by the apple then i looked in my inventory for him and strangely i found my lost oshawot but i didnt found my marshtomp and it isnt in the pc i am using a older version since the latest crashes for me

**Comment by jochuan** [comment]
when i came back to the place and pressed R the marshtomp returned to my inventory something is probably making the pokemons to not return to the owner or something like that

**Comment by Thutmose** [comment]
hmm, do you have the auto-recall thingy enabled? that might be bugged in 1.9+, I will look into it.

**Comment by jochuan** [comment]
Yes i have, after that what happened in my last comment my marshtomp dissapeared again from my inventory so i went to the place that i first lost it and it returned to my inventory but it wasnt possible to use it, so i opened my inventory and replaced the slot of him with normal pokeballs and after that he dissapeared again then i started walking in circles in the area and he returned again and after two tries i  sent it out of the pokeball after that i was frightened of losing my pokemons so i sended them all to the pc

**Comment by Thutmose** [comment]
hmm, try disabling the auto-recall thing and see if it still happens?

**Comment by jochuan** [comment]
until now it didn't happened again after disabling the auto-recall

**Comment by jochuan** [comment]
when you gonna fix the auto-recall i lost a rhyhorn because it wasnt on, the same thing that happened with my chikorita

**Comment by jochuan** [comment]
i think that i know why i lost it it is probably the cull thing that made it disappear it shouldn't work on owned pokemobs and maybe legendary pokemons

**Comment by Thutmose** [comment]
hmm, cull shouldn't affect owned pokemobs, I will check if it does.  As for legendary ones, if It didn't affect them, then players could very easily get legendaries to show up by flying up and down a lot, and eventually the ground will be full of legendaires.

Edit: tested culling, it doesn't affect tame mobs for me

**Comment by jochuan** [comment]
i dont know how to reproduce it either i was on a mine shaft with rhyhorn and some monsters were attacking me at least can you fix the auto-recall ?

**Comment by Thutmose** [comment]
I will try to get auto-recall fixed shortly, I will need to first find out what was going wrong with it.

**Comment by Thutmose** [comment]
I forgot to mention this when I re-enabled it, but see if it works now? I think auto-recall should be fixed now.

**Comment by jochuan** [comment]
until now i didn't had problems using it

**Comment by Philosyang** [comment]
I'm sorry if I've bumped this issue, but I think this issue still exists...
I have already lost 2 pokemon when I'm preparing to fight.
aim, hold the right mouse button, release, and vanish.

The jar is **pokecube-aio-1.12.2-1.6.17.jar**

**Comment by Philosyang** [comment]
I've done some experiments and I've got a conclusion.
When you are aiming a wild pokemon's hitbox with your crosshair and you throw your pokemon no matter the power, when it is too far, your pokemon will disappear.

**Comment by Thutmose** [comment]
how far is "too far"?

**Comment by Thutmose** [comment]
can you get some screenshots of this situation?

**Comment by Thutmose** [comment]
I also cannot replicate this one

**Comment by Philosyang** [comment]
After recording this [video](https://mega.nz/#!RbwUwYCS!RN121BvjEXs7BBqAFtPam2KzKmdWSoRk1IqJGuABNLI), I think I know what's happening.

I first tested at singleplayer, I cannot replicate, too. Therefore I decided to give my server a try, it worked.
When you aim at a wild pokemon and you throw your pokemon to it, your pokemon just travels *really fast* to the destination (wild pokemon) regardless of the distance. My sponge forge config must be cleaning the entities that travels too fast. I'll go and have a check.

**Comment by Philosyang** [comment]
Yeah, it was the removing-entity-which-moves-too-fast thing.
I'm sorry for all the trouble.
Maybe you can set a distance threshold? So that players' pokemon will not be *thrown* to a faraway pokemon at a somewhat unreasonable distance.

To future viewers:
you can just disable sponge movement checks so that the pokemon will no longer be *removed* because of its *thrown speed*.

**Comment by Thutmose** [comment]
I can see about add some threshold configs for this
